"""Summary tables and the combined Markdown/HTML report.

The report is written inside ``results/`` and links the figures with relative
paths, so the whole folder can be zipped, moved or shared and still render.
"""

from __future__ import annotations

import datetime as _dt
import html as _html
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd

from .io_utils import to_markdown_table

if TYPE_CHECKING:  # pragma: no cover
    from .runner import RunOutput

__all__ = ["write_report", "build_summary_markdown", "format_summary"]

_SUMMARY_COLUMNS = ["analysis", "observable", "unit", "n_frames",
                    "mean", "std", "min", "max"]

_CSS = """
:root { color-scheme: light dark; }
body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
       max-width: 1080px; margin: 2rem auto; padding: 0 1.2rem; line-height: 1.55; }
h1 { border-bottom: 2px solid #0072B2; padding-bottom: .3rem; }
h2 { margin-top: 2.4rem; border-bottom: 1px solid #ccc; padding-bottom: .2rem; }
table { border-collapse: collapse; margin: 1rem 0; font-size: .9rem; }
th, td { border: 1px solid #bbb; padding: .35rem .6rem; text-align: right; }
th { background: rgba(0,114,178,.12); text-align: center; }
td:first-child, td:nth-child(2) { text-align: left; }
figure { margin: 1.2rem 0; }
img { max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 4px; }
figcaption { font-size: .82rem; color: #666; margin-top: .3rem; }
.meta { font-size: .9rem; color: #555; }
.note { background: rgba(0,114,178,.07); border-left: 3px solid #0072B2;
        padding: .5rem .8rem; margin: .6rem 0; font-size: .9rem; }
.fail { border-left-color: #D55E00; background: rgba(213,94,0,.08); }
.gallery { display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
           gap: 1rem; }
"""


def format_summary(summary: pd.DataFrame) -> pd.DataFrame:
    """Reorder/round the summary table for display."""
    if summary is None or summary.empty:
        return pd.DataFrame()
    columns = [c for c in _SUMMARY_COLUMNS if c in summary.columns]
    extras = [c for c in summary.columns if c not in columns]
    display = summary[columns + extras].copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].round(3)
    return display


def build_summary_markdown(output: "RunOutput") -> str:
    """Markdown version of the global summary table (mean ± std, min, max)."""
    display = format_summary(output.summary)
    if display.empty:
        return "_No quantitative results were produced._\n"

    compact = pd.DataFrame({
        "Analysis": display["analysis"],
        "Observable": display["observable"],
        "Mean ± SD": [f"{m:.3f} ± {s:.3f}" if pd.notna(s) else f"{m:.3f}"
                      for m, s in zip(display["mean"], display["std"])],
        "Min": display["min"],
        "Max": display["max"],
        "Unit": display["unit"],
        "Frames": display["n_frames"],
    })
    if "occupancy_pct" in display.columns:
        compact["Occupancy (%)"] = display["occupancy_pct"]
    if "frames_below_threshold_%" in display.columns:
        compact["< threshold (%)"] = display["frames_below_threshold_%"]
    return to_markdown_table(compact)


def write_report(output: "RunOutput") -> list[Path]:
    """Write ``summary/summary.md`` plus the requested report formats."""
    paths = output.paths
    files: list[Path] = []

    summary_md = build_summary_markdown(output)
    summary_path = paths.summary / "summary.md"
    summary_path.write_text(
        f"# Summary\n\n{summary_md}\n", encoding="utf-8"
    )
    files.append(summary_path)

    formats = output.config.report.formats
    markdown = _build_markdown(output, summary_md)
    if "markdown" in formats:
        path = paths.root / "report.md"
        path.write_text(markdown, encoding="utf-8")
        files.append(path)
    if "html" in formats:
        path = paths.root / "report.html"
        path.write_text(_build_html(output), encoding="utf-8")
        files.append(path)
    return files


# --------------------------------------------------------------------------- #
# Markdown
# --------------------------------------------------------------------------- #
def _build_markdown(output: "RunOutput", summary_md: str) -> str:
    config = output.config
    lines: list[str] = [f"# {config.report.title}", ""]
    lines += [f"_Generated by md_interactions on "
              f"{_dt.datetime.now().strftime('%Y-%m-%d %H:%M')}_", ""]
    lines += _metadata_lines(output)
    lines += ["", "## Summary", "", summary_md, ""]

    for result in output.results:
        lines.append(f"## {result.title}")
        lines.append("")
        for note in result.notes:
            lines.append(f"> {note}")
        if result.notes:
            lines.append("")
        if result.summary is not None and not result.summary.empty:
            lines.append(to_markdown_table(format_summary(result.summary)))
            lines.append("")
        for name, table in result.tables.items():
            if _is_report_table(name, table):
                lines.append(f"**{name}**")
                lines.append("")
                lines.append(to_markdown_table(table.head(30)))
                lines.append("")
        for plot in result.plots:
            relative = output.paths.relative(plot)
            lines.append(f"![{plot.stem}]({relative})")
            lines.append("")
        data_files = sorted({f"data/{name}.csv" for name in result.tables})
        if data_files:
            lines.append(f"_Data: {', '.join(data_files)}_")
            lines.append("")

    if output.failures:
        lines += ["## Failed analyses", ""]
        for name, message in output.failures:
            lines.append(f"- **{name}**: {message.splitlines()[0]}")
        lines.append("")
    return "\n".join(lines)


def _metadata_lines(output: "RunOutput") -> list[str]:
    config = output.config
    system = output.system
    if system is None:                      # data: mode, no trajectory involved
        dataset = output.dataset
        lines = [
            f"- **Data files**: `{', '.join(p.name for p in dataset.sources)}`",
            f"- **Rows analysed**: {dataset.n_frames}",
            f"- **Observables**: {', '.join(dataset.columns)}",
        ]
        if dataset.replica_labels is not None:
            counts = {name: int(mask.sum())
                      for name, mask in dataset.replica_masks().items()}
            listed = ", ".join(f"{k}: {v}" for k, v in counts.items())
            lines.append(f"- **Replicas**: {listed}")
        if config.source:
            lines.append(f"- **Configuration**: `{config.source.name}`")
        return lines

    trajectories = ", ".join(p.name for p in config.system.trajectory)
    lines = [
        f"- **Topology**: `{config.system.topology.name}`",
        f"- **Trajectory**: `{trajectories}`",
        f"- **Atoms**: {system.universe.atoms.n_atoms}",
        f"- **Frames analysed**: {system.n_frames} "
        f"(start={config.system.frames.start}, stop={config.system.frames.stop}, "
        f"stride={config.system.frames.stride})",
    ]
    if system.time_unit != "frame":
        lines.append(
            f"- **Time range**: {system.times[0]:g} – {system.times[-1]:g} "
            f"{system.time_unit} (dt = {system.dt_per_frame:g} {system.time_unit}/frame)"
        )
    if system.replica_labels is not None:
        counts = {name: int(mask.sum())
                  for name, mask in system.replica_masks().items()}
        listed = ", ".join(f"{k}: {v}" for k, v in counts.items())
        lines.append(f"- **Replicas**: {listed}")
    if config.source:
        lines.append(f"- **Configuration**: `{config.source.name}`")
    return lines


def _is_report_table(name: str, table: pd.DataFrame) -> bool:
    """Only small, human-readable tables are inlined in the report."""
    if name == "replica_overlap" and not table.empty:
        return True
    return name in {"hbonds_detected", "clusters"} and not table.empty


# --------------------------------------------------------------------------- #
# HTML
# --------------------------------------------------------------------------- #
def _build_html(output: "RunOutput") -> str:
    config = output.config
    parts: list[str] = [
        "<!DOCTYPE html>", "<html lang='en'>", "<head>",
        "<meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        f"<title>{_html.escape(config.report.title)}</title>",
        f"<style>{_CSS}</style>", "</head>", "<body>",
        f"<h1>{_html.escape(config.report.title)}</h1>",
        f"<p class='meta'>Generated by md_interactions on "
        f"{_dt.datetime.now().strftime('%Y-%m-%d %H:%M')}</p>",
        "<ul class='meta'>",
    ]
    for line in _metadata_lines(output):
        parts.append("<li>" + _markdown_inline_to_html(line.lstrip("- ")) + "</li>")
    parts.append("</ul>")

    parts.append("<h2>Summary</h2>")
    parts.append(_table_html(format_summary(output.summary)))

    for result in output.results:
        parts.append(f"<h2>{_html.escape(result.title)}</h2>")
        for note in result.notes:
            parts.append(f"<div class='note'>{_html.escape(note)}</div>")
        if result.summary is not None and not result.summary.empty:
            parts.append(_table_html(format_summary(result.summary)))
        for name, table in result.tables.items():
            if _is_report_table(name, table):
                parts.append(f"<h3>{_html.escape(name)}</h3>")
                parts.append(_table_html(table.head(30)))
        if result.plots:
            parts.append("<div class='gallery'>")
            for plot in result.plots:
                relative = _html.escape(output.paths.relative(plot))
                parts.append(
                    f"<figure><img src='{relative}' alt='{_html.escape(plot.stem)}'>"
                    f"<figcaption>{_html.escape(plot.stem)}</figcaption></figure>"
                )
            parts.append("</div>")

    if output.failures:
        parts.append("<h2>Failed analyses</h2>")
        for name, message in output.failures:
            parts.append(
                f"<div class='note fail'><b>{_html.escape(name)}</b>: "
                f"{_html.escape(message.splitlines()[0])}</div>"
            )

    parts += ["</body>", "</html>"]
    return "\n".join(parts)


def _table_html(df: pd.DataFrame) -> str:
    if df is None or df.empty:
        return "<p><i>(no data)</i></p>"
    return df.to_html(index=False, border=0, float_format=lambda v: f"{v:.3f}",
                      na_rep="-")


def _markdown_inline_to_html(text: str) -> str:
    """Minimal ``**bold**`` / ``` `code` ``` conversion for the metadata list."""
    escaped = _html.escape(text)
    for marker, tag in (("**", "b"), ("`", "code")):
        pieces = escaped.split(marker)
        rebuilt = []
        for i, piece in enumerate(pieces):
            rebuilt.append(f"<{tag}>{piece}</{tag}>" if i % 2 else piece)
        escaped = "".join(rebuilt)
    return escaped
