"""Interactive configuration builder (``md-analyzer wizard``).

Writing the YAML by hand has three sharp edges: translating "the Asp20:OD1 –
Arg414:HH12 distance" into MDAnalysis syntax without knowing whether that resid
even exists, getting the indentation right, and discovering which options are
available in the first place.  The wizard removes all three: selections are
written as ``20@OD1`` and validated against the real topology as you type,
the YAML is generated for you, and every menu lists what can be measured.

It is deliberately built on plain ``input()``/``print()`` so it works over SSH
on a cluster with no extra dependencies, and so it can be driven from a script
(or a test) by feeding ``input_fn`` a list of answers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterable

import yaml

from .exceptions import MDInteractionsError

__all__ = ["run_wizard", "AtomResolver", "Prompt"]

_HEADER = """\
# =============================================================================
# Generated by `md-analyzer wizard`
#
#   md-analyzer check -c {name}   # re-validate every selection
#   md-analyzer run   -c {name}   # run the analyses
#
# This file is a normal configuration: edit it by hand whenever you need to.
# Selection syntax: https://userguide.mdanalysis.org/stable/selections.html
# =============================================================================

"""


# --------------------------------------------------------------------------- #
# prompting
# --------------------------------------------------------------------------- #
class Prompt:
    """Thin wrapper around input/print so the wizard can be scripted."""

    def __init__(self, input_fn: Callable[[str], str] = input,
                 print_fn: Callable[..., None] = print) -> None:
        self._input = input_fn
        self._print = print_fn

    # -- output -- #
    def say(self, text: str = "") -> None:
        self._print(text)

    def title(self, text: str) -> None:
        self._print(f"\n{text}")
        self._print("-" * len(text))

    def ok(self, text: str) -> None:
        self._print(f"  [ok] {text}")

    def warn(self, text: str) -> None:
        self._print(f"  [!] {text}")

    # -- input -- #
    def text(self, question: str, default: str | None = None,
             allow_empty: bool = False) -> str:
        suffix = f" [{default}]" if default is not None else ""
        while True:
            answer = self._input(f"{question}{suffix}: ").strip()
            if not answer and default is not None:
                return default
            if answer or allow_empty:
                return answer

    def yes_no(self, question: str, default: bool = False) -> bool:
        suffix = "[s/N]" if not default else "[S/n]"
        while True:
            answer = self._input(f"{question} {suffix}: ").strip().lower()
            if not answer:
                return default
            if answer in {"s", "si", "sí", "y", "yes"}:
                return True
            if answer in {"n", "no"}:
                return False
            self.warn("Responde 's' o 'n'.")

    def number(self, question: str, default: float | None = None,
               cast: Callable = float) -> float | None:
        suffix = f" [{default}]" if default is not None else " [Enter = ninguno]"
        while True:
            answer = self._input(f"{question}{suffix}: ").strip()
            if not answer:
                return default
            try:
                return cast(answer)
            except ValueError:
                self.warn(f"'{answer}' no es un número válido.")

    def choice(self, question: str, options: list[tuple[str, str, str]]) -> str:
        """Menu; ``options`` are ``(key, label, description)`` triples."""
        self.say()
        for key, label, description in options:
            self._print(f"  {key:>3}) {label:<24} {description}")
        valid = {key for key, _l, _d in options}
        while True:
            answer = self._input(f"{question}: ").strip().lower()
            if answer in valid:
                return answer
            self.warn(f"Opción no válida. Elige una de: {', '.join(sorted(valid))}")


# --------------------------------------------------------------------------- #
# selections
# --------------------------------------------------------------------------- #
@dataclass
class ResolvedAtom:
    """An atom (or group) the user picked, with its generated alias."""

    alias: str
    selection: str
    n_atoms: int
    description: str


class AtomResolver:
    """Translates friendly atom specs into validated MDAnalysis selections.

    Accepted forms::

        20@OD1          resid 20, atom OD1
        ASP20@OD1       same, with the residue name checked
        TRH@O2P         by residue name (any residue called TRH)
        20@OD1,OD2      several atoms of the same residue
        resid 20 and name OD1        raw MDAnalysis selection

    Anything starting with ``?`` is a query rather than a selection.
    """

    def __init__(self, universe, prompt: Prompt) -> None:
        self.universe = universe
        self.prompt = prompt
        self._aliases: dict[str, str] = {}

    # -- public API -- #
    @property
    def aliases(self) -> dict[str, str]:
        return dict(self._aliases)

    def ask(self, question: str, expect_single: bool = True) -> ResolvedAtom:
        """Prompt until the user gives a selection that matches something."""
        while True:
            answer = self.prompt.text(question)
            if answer.startswith("?"):
                self._answer_query(answer[1:].strip())
                continue
            try:
                resolved = self.resolve(answer)
            except MDInteractionsError as exc:
                self.prompt.warn(str(exc))
                self.prompt.warn("Escribe '?' para ver la ayuda de búsqueda.")
                continue
            if expect_single and resolved.n_atoms != 1:
                self.prompt.warn(
                    f"{resolved.description} casa {resolved.n_atoms} átomos y aquí "
                    "hace falta exactamente 1. Afina la selección."
                )
                continue
            self.prompt.ok(f"{resolved.description}")
            self._aliases[resolved.alias] = resolved.selection
            return resolved

    def resolve(self, text: str) -> ResolvedAtom:
        """Turn one spec into a validated :class:`ResolvedAtom`."""
        text = text.strip()
        if not text:
            raise MDInteractionsError("Selección vacía.")
        selection, alias = self._to_selection(text)
        try:
            group = self.universe.select_atoms(selection)
        except Exception as exc:
            raise MDInteractionsError(f"Selección inválida: {exc}") from exc
        if group.n_atoms == 0:
            raise MDInteractionsError(
                f'"{selection}" no casa ningún átomo en esta topología.'
            )
        # Prefer an alias built from what actually matched (ASP20_OD1) over the
        # one guessed from the raw input (20_OD1): the YAML stays readable.
        if group.n_atoms == 1:
            atom = group[0]
            description = f"{atom.resname}{atom.resid}:{atom.name} (1 átomo)"
            alias = f"{atom.resname}{atom.resid}_{atom.name}"
        elif group.residues.n_residues == 1:
            residue = group.residues[0]
            names = "_".join(group.names[:4])
            description = (f"{residue.resname}{residue.resid}:"
                           f"{','.join(group.names)} ({group.n_atoms} átomos)")
            alias = f"{residue.resname}{residue.resid}_{names}"
        else:
            residues = sorted({f"{r.resname}{r.resid}" for r in group.residues})
            shown = ", ".join(residues[:3]) + ("..." if len(residues) > 3 else "")
            description = f"{group.n_atoms} átomos ({shown})"
            alias = alias or f"grupo_{len(self._aliases) + 1}"
        return ResolvedAtom(alias=_safe_alias(alias), selection=selection,
                            n_atoms=group.n_atoms, description=description)

    # -- internals -- #
    def _to_selection(self, text: str) -> tuple[str, str | None]:
        """``(MDAnalysis selection, suggested alias)``."""
        if "@" not in text:
            return text, None                      # raw MDAnalysis selection

        residue_part, _sep, atom_part = text.partition("@")
        residue_part = residue_part.strip()
        atoms = [a for a in atom_part.replace(",", " ").split() if a]
        if not residue_part or not atoms:
            raise MDInteractionsError(
                "Formato esperado: residuo@átomo, por ejemplo 20@OD1 o TRH@O2P."
            )

        if residue_part.isdigit():
            residue_selection = f"resid {residue_part}"
            alias_residue = residue_part
        elif residue_part.isalpha():
            residue_selection = f"resname {residue_part.upper()}"
            alias_residue = residue_part.upper()
        else:
            name = "".join(c for c in residue_part if c.isalpha()).upper()
            number = "".join(c for c in residue_part if c.isdigit())
            if not name or not number:
                raise MDInteractionsError(
                    f"No entiendo el residuo '{residue_part}'. Usa 20, ASP20 o TRH."
                )
            self._check_resname(int(number), name)
            residue_selection = f"resid {number}"
            alias_residue = f"{name}{number}"

        selection = f"{residue_selection} and name {' '.join(atoms)}"
        return selection, f"{alias_residue}_{'_'.join(atoms)}"

    def _check_resname(self, resid: int, expected: str) -> None:
        group = self.universe.select_atoms(f"resid {resid}")
        if group.n_atoms == 0:
            raise MDInteractionsError(f"El residuo {resid} no existe en la topología.")
        actual = group.residues[0].resname
        if actual.upper() != expected.upper():
            raise MDInteractionsError(
                f"El residuo {resid} es {actual}, no {expected}. "
                f"Usa '?{expected}' para listar los {expected} de la topología."
            )

    def _answer_query(self, query: str) -> None:
        """Handle the ``?`` helpers that make the topology explorable."""
        universe = self.universe
        say = self.prompt.say
        if not query or query in {"help", "ayuda"}:
            say("  Formatos aceptados:")
            say("    20@OD1            resid 20, átomo OD1")
            say("    ASP20@OD1         igual, comprobando que 20 es un ASP")
            say("    TRH@O2P           por nombre de residuo")
            say("    20@OD1,OD2        varios átomos del mismo residuo")
            say("    resid 20 and name OD1     selección MDAnalysis literal")
            say("  Búsquedas:")
            say("    ?20               muestra el residuo 20 y sus átomos")
            say("    ?ARG              lista todos los ARG de la topología")
            say("    ?ligandos         lista los residuos no proteicos ni agua")
            return

        if query.isdigit():
            group = universe.select_atoms(f"resid {query}")
            if group.n_atoms == 0:
                self.prompt.warn(f"El residuo {query} no existe.")
                return
            residue = group.residues[0]
            say(f"  resid {query} = {residue.resname}")
            say(f"    átomos: {', '.join(residue.atoms.names)}")
            return

        if query.lower() in {"ligandos", "ligands", "resnames"}:
            protein_like = set(universe.select_atoms("protein").residues.resnames)
            water = {"WAT", "HOH", "SOL", "TIP3", "T3P"}
            others: dict[str, int] = {}
            for resname in universe.residues.resnames:
                if resname not in protein_like and resname not in water:
                    others[resname] = others.get(resname, 0) + 1
            if not others:
                self.prompt.warn("No hay residuos no proteicos aparte del disolvente.")
                return
            say("  residuos no proteicos:")
            for resname, count in sorted(others.items(), key=lambda kv: -kv[1])[:20]:
                resids = [int(r.resid) for r in
                          universe.select_atoms(f"resname {resname}").residues][:8]
                say(f"    {resname:<6} x{count:<5} resid: {resids}")
            return

        group = universe.select_atoms(f"resname {query.upper()}")
        if group.n_atoms == 0:
            self.prompt.warn(f"No hay residuos llamados '{query}'.")
            return
        resids = [int(r.resid) for r in group.residues]
        say(f"  {query.upper()}: {len(resids)} residuo(s) -> resid {resids}")
        say(f"    átomos del primero: {', '.join(group.residues[0].atoms.names)}")


def _safe_alias(name: str) -> str:
    keep = [c if (c.isalnum() or c == "_") else "_" for c in str(name)]
    return "".join(keep).strip("_") or "sel"


# --------------------------------------------------------------------------- #
# the wizard itself
# --------------------------------------------------------------------------- #
@dataclass
class _Draft:
    """Accumulates the configuration while the user answers."""

    system: dict = field(default_factory=dict)
    output: dict = field(default_factory=dict)
    selections: dict = field(default_factory=dict)
    analyses: dict = field(default_factory=dict)
    report: dict = field(default_factory=dict)
    observables: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        config: dict = {"system": self.system}
        if self.output:
            config["output"] = self.output
        if self.selections:
            config["selections"] = self.selections
        config["analyses"] = self.analyses
        if self.report:
            config["report"] = self.report
        return config


_MENU = [
    ("1", "distancia", "entre dos átomos o grupos (con umbral opcional)"),
    ("2", "ángulo", "definido por tres átomos"),
    ("3", "diedro", "definido por cuatro átomos"),
    ("4", "puente de H", "distancia D–A, ángulo D–H···A y ocupación"),
    ("5", "RMSD", "global o local (ajuste sobre una selección, medida en otra)"),
    ("6", "RMSF", "fluctuación por residuo"),
    ("7", "radio de giro", "compactación de un dominio o del sitio activo"),
    ("8", "RDF", "g(r) y número de coordinación entre dos selecciones"),
    ("9", "clustering", "estados conformacionales + PDB representativo"),
    ("10", "mapa 2D", "densidad / energía libre aparente de dos observables"),
    ("f", "terminar", "escribir el YAML con lo añadido hasta ahora"),
]


def run_wizard(
    topology: str | Path | None = None,
    trajectory: Iterable[str | Path] | None = None,
    output: str | Path = "config.yaml",
    input_fn: Callable[[str], str] = input,
    print_fn: Callable[..., None] = print,
    force: bool = False,
) -> Path:
    """Ask the questions, validate against the topology and write the YAML."""
    import MDAnalysis as mda

    prompt = Prompt(input_fn, print_fn)
    prompt.say("=== md_interactions — asistente de configuración ===")
    prompt.say("Enter acepta el valor por defecto; '?' muestra ayuda en las selecciones.")

    # -- 1. system ------------------------------------------------------- #
    prompt.title("1/4  Sistema")
    topology = topology or prompt.text("Topología (.prmtop/.parm7/.pdb)")
    topology_path = Path(str(topology))
    if not topology_path.is_file():
        raise MDInteractionsError(f"No encuentro la topología: {topology_path}")

    try:
        universe = mda.Universe(str(topology_path))
    except Exception as exc:
        raise MDInteractionsError(f"No pude leer la topología: {exc}") from exc

    protein = universe.select_atoms("protein")
    prompt.ok(f"{universe.atoms.n_atoms} átomos, "
              f"{universe.residues.n_residues} residuos "
              f"({protein.residues.n_residues} de proteína)")

    draft = _Draft()
    draft.system["topology"] = str(topology_path)

    trajectory = list(trajectory or [])
    if not trajectory:
        answer = prompt.text("Trayectoria(s), separadas por espacios", default="",
                             allow_empty=True)
        trajectory = answer.split()
    if trajectory:
        if len(trajectory) > 1 and prompt.yes_no(
            "¿Son réplicas independientes (en vez de tramos de una misma run)?",
            default=True,
        ):
            draft.system["replicas"] = {
                f"rep{i + 1}": [str(path)] for i, path in enumerate(trajectory)
            }
            prompt.ok(f"{len(trajectory)} réplicas declaradas")
        else:
            draft.system["trajectory"] = [str(p) for p in trajectory]
    else:
        draft.system["trajectory"] = ["CAMBIAME.nc"]
        prompt.warn("Sin trayectoria: pon la ruta en 'system.trajectory' antes de correr.")

    unit = prompt.text("Unidad de tiempo (ps/ns/frame)", default="ns")
    dt = prompt.number("Tiempo entre frames guardados (Enter = leer de la trayectoria)")
    draft.system["time"] = {"dt": dt, "unit": unit}
    stride = prompt.number("Stride (analizar 1 de cada N frames)", default=1, cast=int)
    if stride and stride > 1:
        draft.system["frames"] = {"stride": int(stride)}

    # -- 2. interactions ------------------------------------------------- #
    prompt.title("2/4  Interacciones a medir")
    resolver = AtomResolver(universe, prompt)
    while True:
        option = prompt.choice("¿Qué añado?", _MENU)
        if option == "f":
            break
        _dispatch(option, prompt, resolver, draft)

    draft.selections = resolver.aliases

    # -- 3. output ------------------------------------------------------- #
    prompt.title("3/4  Salida")
    draft.output["directory"] = prompt.text("Carpeta de resultados", default="results")
    formats = prompt.text("Formatos de figura", default="png pdf").split()
    draft.output["formats"] = formats
    draft.output["dpi"] = int(prompt.number("DPI", default=300, cast=int))
    if prompt.yes_no("¿Generar informe Markdown + HTML?", default=True):
        draft.report = {"enabled": True, "formats": ["markdown", "html"]}
    else:
        draft.report = {"enabled": False}

    # -- 4. write -------------------------------------------------------- #
    prompt.title("4/4  Escribiendo la configuración")
    if not draft.analyses:
        prompt.warn("No añadiste ningún análisis; el YAML saldrá vacío de 'analyses'.")

    destination = Path(str(output))
    if destination.exists() and not force:
        if not prompt.yes_no(f"{destination} ya existe. ¿Sobrescribir?", default=False):
            destination = Path(prompt.text("Nombre alternativo", default="config_2.yaml"))

    destination.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(draft.to_dict(), sort_keys=False, allow_unicode=True,
                          default_flow_style=False)
    destination.write_text(_HEADER.format(name=destination.name) + body, encoding="utf-8")

    prompt.ok(f"escrito {destination}")
    prompt.say(f"\nSiguiente paso:\n  md-analyzer check -c {destination}\n"
               f"  md-analyzer run   -c {destination}")
    return destination


# --------------------------------------------------------------------------- #
# one handler per menu entry
# --------------------------------------------------------------------------- #
def _dispatch(option: str, prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    handlers = {
        "1": _add_distance,
        "2": _add_angle,
        "3": _add_dihedral,
        "4": _add_hbond,
        "5": _add_rmsd,
        "6": _add_rmsf,
        "7": _add_rgyr,
        "8": _add_rdf,
        "9": _add_clustering,
        "10": _add_map,
    }
    handlers[option](prompt, resolver, draft)


def _section(draft: _Draft, name: str, default: dict) -> dict:
    return draft.analyses.setdefault(name, default)


def _add_distance(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "distances", {"enabled": True, "pairs": []})
    mode = prompt.choice("Tipo de distancia", [
        ("1", "átomo–átomo", "un átomo en cada extremo (lo habitual)"),
        ("2", "centro de masas", "entre los COM de dos grupos"),
        ("3", "mínima", "la distancia más corta entre dos grupos (p. ej. el agua más cercana)"),
    ])
    single = mode == "1"
    first = resolver.ask("  Átomo/grupo A", expect_single=single)
    second = resolver.ask("  Átomo/grupo B", expect_single=single)
    default_name = f"d_{first.alias}_{second.alias}"[:40]
    name = prompt.text("  Nombre", default=default_name)
    entry = {"name": name, "atoms": [first.alias, second.alias],
             "label": f"{first.description.split(' (')[0]} – "
                      f"{second.description.split(' (')[0]}"}
    if mode == "2":
        entry["mode"] = "com"
    elif mode == "3":
        entry["mode"] = "min"
    threshold = prompt.number("  Umbral en Å (para el % de frames por debajo)")
    if threshold is not None:
        entry["threshold"] = threshold
    section["pairs"].append(entry)
    draft.observables.append(name)
    prompt.ok(f"añadida la distancia '{name}'")


def _add_geometry(prompt: Prompt, resolver: AtomResolver, draft: _Draft,
                  key: str, n_atoms: int, prefix: str) -> None:
    section = _section(draft, key, {"enabled": True, "definitions": []})
    atoms = [resolver.ask(f"  Átomo {i + 1} de {n_atoms}") for i in range(n_atoms)]
    default_name = f"{prefix}_{atoms[0].alias}"[:40]
    name = prompt.text("  Nombre", default=default_name)
    section["definitions"].append({
        "name": name,
        "atoms": [a.alias for a in atoms],
        "label": " – ".join(a.description.split(" (")[0] for a in atoms),
    })
    draft.observables.append(name)
    prompt.ok(f"añadido '{name}'")


def _add_angle(prompt, resolver, draft) -> None:
    _add_geometry(prompt, resolver, draft, "angles", 3, "a")


def _add_dihedral(prompt, resolver, draft) -> None:
    _add_geometry(prompt, resolver, draft, "dihedrals", 4, "chi")


def _add_hbond(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "hbonds", {
        "enabled": True, "d_a_cutoff": 3.5, "d_h_a_angle_cutoff": 150, "pairs": [],
    })
    prompt.say("  El donor es el átomo pesado (N, O...), no el hidrógeno.")
    donor = resolver.ask("  Donor (átomo pesado)")
    acceptor = resolver.ask("  Aceptor", expect_single=False)
    entry = {"name": prompt.text("  Nombre", default=f"hb_{donor.alias}_{acceptor.alias}"[:40]),
             "donor": donor.alias, "acceptor": acceptor.alias}
    if prompt.yes_no("  ¿Especificar el hidrógeno concreto? "
                     "(por defecto se elige el mejor orientado)", default=False):
        entry["hydrogen"] = resolver.ask("  Hidrógeno").alias
    section["pairs"].append(entry)
    draft.observables.append(entry["name"])
    prompt.ok(f"añadido el puente de H '{entry['name']}'")


def _add_rmsd(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "rmsd", {"enabled": True, "ref_frame": 0, "groups": []})
    prompt.say("  Selección a MEDIR (p. ej. backbone, resname LIG, o un grupo del sitio activo).")
    measured = resolver.ask("  Selección medida", expect_single=False)
    entry = {"name": prompt.text("  Nombre", default=measured.alias),
             "selection": measured.alias}
    if prompt.yes_no("  ¿Ajustar (fit) sobre una selección distinta? "
                     "(RMSD local: ajustar en la proteína, medir el ligando)",
                     default=False):
        fit = resolver.ask("  Selección de ajuste", expect_single=False)
        entry["superposition"] = fit.alias
    section["groups"].append(entry)
    draft.observables.append(entry["name"])
    prompt.ok(f"añadido el RMSD '{entry['name']}'")


def _add_rmsf(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    selection = prompt.text("  Selección", default="protein and name CA")
    entry = {"enabled": True, "selection": selection, "align": True}
    highlight = prompt.text("  Residuos a destacar (números separados por espacios)",
                            default="", allow_empty=True)
    if highlight.strip():
        entry["highlight"] = [int(x) for x in highlight.split() if x.isdigit()]
    draft.analyses["rmsf"] = entry
    prompt.ok("añadido el RMSF por residuo")


def _add_rgyr(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "radius_of_gyration", {"enabled": True, "groups": []})
    group = resolver.ask("  Selección", expect_single=False)
    name = prompt.text("  Nombre", default=f"rg_{group.alias}"[:40])
    section["groups"].append({"name": name, "selection": group.alias})
    draft.observables.append(name)
    prompt.ok(f"añadido el radio de giro '{name}'")


def _add_rdf(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "rdf", {"enabled": True, "pairs": []})
    first = resolver.ask("  Selección central (g1)", expect_single=False)
    second = resolver.ask("  Selección del entorno (g2, p. ej. el oxígeno del agua)",
                          expect_single=False)
    name = prompt.text("  Nombre", default=f"rdf_{first.alias}_{second.alias}"[:40])
    rmax = prompt.number("  Radio máximo en Å", default=12.0)
    section["pairs"].append({"name": name, "g1": first.alias, "g2": second.alias,
                             "nbins": 120, "range": [0.0, float(rmax)]})
    prompt.ok(f"añadida la RDF '{name}'")


def _add_clustering(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    group = resolver.ask("  Selección sobre la que agrupar "
                         "(p. ej. el sitio activo sin hidrógenos)", expect_single=False)
    n_clusters = int(prompt.number("  Número de clústeres", default=3, cast=int))
    draft.analyses["clustering"] = {
        "enabled": True, "selection": group.alias, "method": "hierarchical",
        "n_clusters": n_clusters, "write_structures": True,
    }
    prompt.ok(f"añadido el clustering en {n_clusters} clústeres")


def _add_map(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    if len(draft.observables) < 2:
        prompt.warn("Necesitas al menos dos observables ya definidos "
                    "(distancias, ángulos, RMSD...). Añádelos antes.")
        return
    prompt.say(f"  Observables disponibles: {', '.join(draft.observables)}")
    section = _section(draft, "free_energy_maps",
                       {"enabled": True, "temperature": 300.0, "maps": []})
    while True:
        x = prompt.text("  Eje X", default=draft.observables[0])
        if x in draft.observables:
            break
        prompt.warn(f"'{x}' no está definido.")
    while True:
        y = prompt.text("  Eje Y", default=draft.observables[1])
        if y in draft.observables:
            break
        prompt.warn(f"'{y}' no está definido.")
    name = prompt.text("  Nombre", default=f"fes_{x}_{y}"[:40])
    free_energy = prompt.yes_no("  ¿Convertir a energía libre aparente (-kT ln P)?",
                                default=True)
    section["maps"].append({"name": name, "x": x, "y": y, "bins": 60,
                            "free_energy": free_energy})
    prompt.ok(f"añadido el mapa '{name}'")
