"""Interactive configuration builder (``md-analyzer wizard``).

Writing the YAML by hand has three sharp edges: translating "the Asp20:OD1 –
Arg414:HH12 distance" into MDAnalysis syntax without knowing whether that resid
even exists, getting the indentation right, and discovering which options are
available in the first place.  The wizard removes all three: selections are
written as ``20@OD1`` and validated against the real topology as you type,
the YAML is generated for you, and every menu lists what can be measured.

It is deliberately built on plain ``input()``/``print()`` so it works over SSH
on a cluster with no extra dependencies, and so it can be driven from a script
(or a test) by feeding ``input_fn`` a list of answers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterable

import yaml

from .exceptions import MDInteractionsError

__all__ = ["run_wizard", "AtomResolver", "Prompt"]

_HEADER = """\
# =============================================================================
# Generated by `md-analyzer wizard`
#
#   md-analyzer check -c {name}   # re-validate every selection
#   md-analyzer run   -c {name}   # run the analyses
#
# This file is a normal configuration: edit it by hand whenever you need to.
# Selection syntax: https://userguide.mdanalysis.org/stable/selections.html
# =============================================================================

"""


# --------------------------------------------------------------------------- #
# prompting
# --------------------------------------------------------------------------- #
class Prompt:
    """Thin wrapper around input/print so the wizard can be scripted."""

    def __init__(self, input_fn: Callable[[str], str] = input,
                 print_fn: Callable[..., None] = print) -> None:
        self._input = input_fn
        self._print = print_fn

    # -- output -- #
    def say(self, text: str = "") -> None:
        self._print(text)

    def title(self, text: str) -> None:
        self._print(f"\n{text}")
        self._print("-" * len(text))

    def ok(self, text: str) -> None:
        self._print(f"  [ok] {text}")

    def warn(self, text: str) -> None:
        self._print(f"  [!] {text}")

    # -- input -- #
    def text(self, question: str, default: str | None = None,
             allow_empty: bool = False) -> str:
        suffix = f" [{default}]" if default is not None else ""
        while True:
            answer = self._input(f"{question}{suffix}: ").strip()
            if not answer and default is not None:
                return default
            if answer or allow_empty:
                return answer

    def yes_no(self, question: str, default: bool = False) -> bool:
        suffix = "[s/N]" if not default else "[S/n]"
        while True:
            answer = self._input(f"{question} {suffix}: ").strip().lower()
            if not answer:
                return default
            if answer in {"y", "yes", "s", "si"}:
                return True
            if answer in {"n", "no"}:
                return False
            self.warn("Please answer 'y' or 'n'.")

    def number(self, question: str, default: float | None = None,
               cast: Callable = float) -> float | None:
        suffix = f" [{default}]" if default is not None else " [Enter = none]"
        while True:
            answer = self._input(f"{question}{suffix}: ").strip()
            if not answer:
                return default
            try:
                return cast(answer)
            except ValueError:
                self.warn(f"'{answer}' is not a valid number.")

    def choice(self, question: str, options: list[tuple[str, str, str]]) -> str:
        """Menu; ``options`` are ``(key, label, description)`` triples."""
        self.say()
        for key, label, description in options:
            self._print(f"  {key:>3}) {label:<24} {description}")
        valid = {key for key, _l, _d in options}
        while True:
            answer = self._input(f"{question}: ").strip().lower()
            if answer in valid:
                return answer
            self.warn(f"Invalid option. Choose one of: {', '.join(sorted(valid))}")


# --------------------------------------------------------------------------- #
# selections
# --------------------------------------------------------------------------- #
@dataclass
class ResolvedAtom:
    """An atom (or group) the user picked, with its generated alias."""

    alias: str
    selection: str
    n_atoms: int
    description: str


class AtomResolver:
    """Translates friendly atom specs into validated MDAnalysis selections.

    Accepted forms::

        20@OD1          resid 20, atom OD1
        ASP20@OD1       same, with the residue name checked
        TRH@O2P         by residue name (any residue called TRH)
        20@OD1,OD2      several atoms of the same residue
        resid 20 and name OD1        raw MDAnalysis selection

    Anything starting with ``?`` is a query rather than a selection.
    """

    def __init__(self, universe, prompt: Prompt) -> None:
        self.universe = universe
        self.prompt = prompt
        self._aliases: dict[str, str] = {}

    # -- public API -- #
    @property
    def aliases(self) -> dict[str, str]:
        return dict(self._aliases)

    def ask(self, question: str, expect_single: bool = True) -> ResolvedAtom:
        """Prompt until the user gives a selection that matches something."""
        while True:
            answer = self.prompt.text(question)
            if answer.startswith("?"):
                self._answer_query(answer[1:].strip())
                continue
            try:
                resolved = self.resolve(answer)
            except MDInteractionsError as exc:
                self.prompt.warn(str(exc))
                self.prompt.warn("Type '?' to see the search help.")
                continue
            if expect_single and resolved.n_atoms != 1:
                self.prompt.warn(
                    f"{resolved.description} matches {resolved.n_atoms} atoms but exactly "
                    "1 is needed here. Refine the selection."
                )
                continue
            self.prompt.ok(f"{resolved.description}")
            self._aliases[resolved.alias] = resolved.selection
            return resolved

    def resolve(self, text: str) -> ResolvedAtom:
        """Turn one spec into a validated :class:`ResolvedAtom`."""
        text = text.strip()
        if not text:
            raise MDInteractionsError("Empty selection.")
        selection, alias = self._to_selection(text)
        try:
            group = self.universe.select_atoms(selection)
        except Exception as exc:
            raise MDInteractionsError(f"Invalid selection: {exc}") from exc
        if group.n_atoms == 0:
            raise MDInteractionsError(
                f'"{selection}" matches no atom in this topology.'
            )
        # Prefer an alias built from what actually matched (ASP20_OD1) over the
        # one guessed from the raw input (20_OD1): the YAML stays readable.
        if group.n_atoms == 1:
            atom = group[0]
            description = f"{atom.resname}{atom.resid}:{atom.name} (1 atom)"
            alias = f"{atom.resname}{atom.resid}_{atom.name}"
        elif group.residues.n_residues == 1:
            residue = group.residues[0]
            names = "_".join(group.names[:4])
            description = (f"{residue.resname}{residue.resid}:"
                           f"{','.join(group.names)} ({group.n_atoms} atoms)")
            alias = f"{residue.resname}{residue.resid}_{names}"
        else:
            residues = sorted({f"{r.resname}{r.resid}" for r in group.residues})
            shown = ", ".join(residues[:3]) + ("..." if len(residues) > 3 else "")
            description = f"{group.n_atoms} atoms ({shown})"
            alias = alias or f"grupo_{len(self._aliases) + 1}"
        return ResolvedAtom(alias=_safe_alias(alias), selection=selection,
                            n_atoms=group.n_atoms, description=description)

    # -- internals -- #
    def _to_selection(self, text: str) -> tuple[str, str | None]:
        """``(MDAnalysis selection, suggested alias)``."""
        if "@" not in text:
            return text, None                      # raw MDAnalysis selection

        residue_part, _sep, atom_part = text.partition("@")
        residue_part = residue_part.strip()
        atoms = [a for a in atom_part.replace(",", " ").split() if a]
        if not residue_part or not atoms:
            raise MDInteractionsError(
                "Expected format: residue@atom, for example 20@OD1 or TRH@O2P."
            )

        if residue_part.isdigit():
            residue_selection = f"resid {residue_part}"
            alias_residue = residue_part
        elif residue_part.isalpha():
            residue_selection = f"resname {residue_part.upper()}"
            alias_residue = residue_part.upper()
        else:
            name = "".join(c for c in residue_part if c.isalpha()).upper()
            number = "".join(c for c in residue_part if c.isdigit())
            if not name or not number:
                raise MDInteractionsError(
                    f"Cannot read the residue '{residue_part}'. Use 20, ASP20 or TRH."
                )
            self._check_resname(int(number), name)
            residue_selection = f"resid {number}"
            alias_residue = f"{name}{number}"

        selection = f"{residue_selection} and name {' '.join(atoms)}"
        return selection, f"{alias_residue}_{'_'.join(atoms)}"

    def _check_resname(self, resid: int, expected: str) -> None:
        group = self.universe.select_atoms(f"resid {resid}")
        if group.n_atoms == 0:
            raise MDInteractionsError(f"Residue {resid} does not exist in this topology.")
        actual = group.residues[0].resname
        if actual.upper() != expected.upper():
            raise MDInteractionsError(
                f"Residue {resid} is {actual}, not {expected}. "
                f"Use '?{expected}' to list the {expected} residues in the topology."
            )

    def _answer_query(self, query: str) -> None:
        """Handle the ``?`` helpers that make the topology explorable."""
        universe = self.universe
        say = self.prompt.say
        if not query or query in {"help", "ayuda"}:
            say("  Accepted formats:")
            say("    20@OD1            resid 20, atom OD1")
            say("    ASP20@OD1         same, checking that residue 20 is an ASP")
            say("    TRH@O2P           by residue name")
            say("    20@OD1,OD2        several atoms of the same residue")
            say("    resid 20 and name OD1     literal MDAnalysis selection")
            say("  Searches:")
            say("    ?20               show residue 20 and its atoms")
            say("    ?ARG              list every ARG in the topology")
            say("    ?ligands          list residues that are neither protein nor water")
            return

        if query.isdigit():
            group = universe.select_atoms(f"resid {query}")
            if group.n_atoms == 0:
                self.prompt.warn(f"Residue {query} does not exist.")
                return
            residue = group.residues[0]
            say(f"  resid {query} = {residue.resname}")
            say(f"    atoms: {', '.join(residue.atoms.names)}")
            return

        if query.lower() in {"ligands", "ligandos", "resnames"}:
            protein_like = set(universe.select_atoms("protein").residues.resnames)
            water = {"WAT", "HOH", "SOL", "TIP3", "T3P"}
            others: dict[str, int] = {}
            for resname in universe.residues.resnames:
                if resname not in protein_like and resname not in water:
                    others[resname] = others.get(resname, 0) + 1
            if not others:
                self.prompt.warn("There are no non-protein residues besides the solvent.")
                return
            say("  residues no proteicos:")
            for resname, count in sorted(others.items(), key=lambda kv: -kv[1])[:20]:
                resids = [int(r.resid) for r in
                          universe.select_atoms(f"resname {resname}").residues][:8]
                say(f"    {resname:<6} x{count:<5} resid: {resids}")
            return

        group = universe.select_atoms(f"resname {query.upper()}")
        if group.n_atoms == 0:
            self.prompt.warn(f"No hay residues llamados '{query}'.")
            return
        resids = [int(r.resid) for r in group.residues]
        say(f"  {query.upper()}: {len(resids)} residue(s) -> resid {resids}")
        say(f"    atoms of the first one: {', '.join(group.residues[0].atoms.names)}")


def _safe_alias(name: str) -> str:
    keep = [c if (c.isalnum() or c == "_") else "_" for c in str(name)]
    return "".join(keep).strip("_") or "sel"


# --------------------------------------------------------------------------- #
# the wizard itself
# --------------------------------------------------------------------------- #
@dataclass
class _Draft:
    """Accumulates the configuration while the user answers."""

    system: dict = field(default_factory=dict)
    output: dict = field(default_factory=dict)
    selections: dict = field(default_factory=dict)
    analyses: dict = field(default_factory=dict)
    report: dict = field(default_factory=dict)
    observables: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        config: dict = {"system": self.system}
        if self.output:
            config["output"] = self.output
        if self.selections:
            config["selections"] = self.selections
        config["analyses"] = self.analyses
        if self.report:
            config["report"] = self.report
        return config


_MENU = [
    ("1", "distance", "between two atoms or groups (optional threshold)"),
    ("2", "angle", "defined by three atoms"),
    ("3", "dihedral", "defined by four atoms"),
    ("4", "hydrogen bond", "D-A distance, D-H...A angle and occupancy"),
    ("5", "RMSD", "global or local (fit on one selection, measure another)"),
    ("6", "RMSF", "per-residue fluctuation"),
    ("7", "radius of gyration", "compaction of a domain or the active site"),
    ("8", "RDF", "g(r), solvation shell and coordination number"),
    ("9", "clustering", "conformational states + representative PDB"),
    ("10", "2D map", "density / apparent free energy of two observables"),
    ("f", "finish", "write the YAML with whatever has been added"),
]


def run_wizard(
    topology: str | Path | None = None,
    trajectory: Iterable[str | Path] | None = None,
    output: str | Path = "config.yaml",
    input_fn: Callable[[str], str] = input,
    print_fn: Callable[..., None] = print,
    force: bool = False,
) -> Path:
    """Ask the questions, validate against the topology and write the YAML."""
    import MDAnalysis as mda

    prompt = Prompt(input_fn, print_fn)
    prompt.say("=== md_interactions - configuration wizard ===")
    prompt.say("Enter accepts the default; type '?' for help on any selection.")

    # -- 1. system ------------------------------------------------------- #
    prompt.title("1/4  System")
    topology = topology or prompt.text("Topology (.prmtop/.parm7/.pdb)")
    topology_path = Path(str(topology))
    if not topology_path.is_file():
        raise MDInteractionsError(f"Topology not found: {topology_path}")

    try:
        universe = mda.Universe(str(topology_path))
    except Exception as exc:
        raise MDInteractionsError(f"Could not read the topology: {exc}") from exc

    protein = universe.select_atoms("protein")
    prompt.ok(f"{universe.atoms.n_atoms} atoms, "
              f"{universe.residues.n_residues} residues "
              f"({protein.residues.n_residues} protein)")

    draft = _Draft()
    draft.system["topology"] = str(topology_path)

    trajectory = list(trajectory or [])
    if not trajectory:
        answer = prompt.text("Trajectory file(s), space separated", default="",
                             allow_empty=True)
        trajectory = answer.split()
    if trajectory:
        if len(trajectory) > 1 and prompt.yes_no(
            "Are these independent replicas (rather than pieces of a single run)?",
            default=True,
        ):
            draft.system["replicas"] = {
                f"rep{i + 1}": [str(path)] for i, path in enumerate(trajectory)
            }
            prompt.ok(f"{len(trajectory)} replicas declared")
        else:
            draft.system["trajectory"] = [str(p) for p in trajectory]
    else:
        draft.system["trajectory"] = ["CAMBIAME.nc"]
        prompt.warn("No trajectory given: set the path in 'system.trajectory' before running.")

    unit = prompt.text("Time unit (ps/ns/frame)", default="ns")
    dt = prompt.number("Time between saved frames (Enter = read it from the trajectory)")
    draft.system["time"] = {"dt": dt, "unit": unit}
    stride = prompt.number("Stride (analyse 1 frame every N)", default=1, cast=int)
    if stride and stride > 1:
        draft.system["frames"] = {"stride": int(stride)}

    # -- 2. interactions ------------------------------------------------- #
    prompt.title("2/4  Interactions to measure")
    resolver = AtomResolver(universe, prompt)
    while True:
        option = prompt.choice("What shall I add?", _MENU)
        if option == "f":
            break
        _dispatch(option, prompt, resolver, draft)

    draft.selections = resolver.aliases

    # -- 3. output ------------------------------------------------------- #
    prompt.title("3/4  Output")
    draft.output["directory"] = prompt.text("Results directory", default="results")
    formats = prompt.text("Figure formats", default="png pdf").split()
    draft.output["formats"] = formats
    draft.output["dpi"] = int(prompt.number("DPI", default=300, cast=int))
    if prompt.yes_no("Generate a Markdown + HTML report?", default=True):
        draft.report = {"enabled": True, "formats": ["markdown", "html"]}
    else:
        draft.report = {"enabled": False}

    # -- 4. write -------------------------------------------------------- #
    prompt.title("4/4  Writing the configuration")
    if not draft.analyses:
        prompt.warn("No analysis was added; the 'analyses' section will be empty.")

    destination = Path(str(output))
    if destination.exists() and not force:
        if not prompt.yes_no(f"{destination} already exists. Overwrite?", default=False):
            destination = Path(prompt.text("Alternative name", default="config_2.yaml"))

    destination.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(draft.to_dict(), sort_keys=False, allow_unicode=True,
                          default_flow_style=False)
    destination.write_text(_HEADER.format(name=destination.name) + body, encoding="utf-8")

    prompt.ok(f"written {destination}")
    prompt.say(f"\nNext step:\n  md-analyzer check -c {destination}\n"
               f"  md-analyzer run   -c {destination}")
    return destination


# --------------------------------------------------------------------------- #
# one handler per menu entry
# --------------------------------------------------------------------------- #
def _dispatch(option: str, prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    handlers = {
        "1": _add_distance,
        "2": _add_angle,
        "3": _add_dihedral,
        "4": _add_hbond,
        "5": _add_rmsd,
        "6": _add_rmsf,
        "7": _add_rgyr,
        "8": _add_rdf,
        "9": _add_clustering,
        "10": _add_map,
    }
    handlers[option](prompt, resolver, draft)


def _section(draft: _Draft, name: str, default: dict) -> dict:
    return draft.analyses.setdefault(name, default)


def _add_distance(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "distances", {"enabled": True, "pairs": []})
    mode = prompt.choice("Distance type", [
        ("1", "atom-atom", "one atom at each end (the usual case)"),
        ("2", "centre of mass", "between the COM of two groups"),
        ("3", "minimum", "shortest distance between two groups (e.g. the nearest water)"),
    ])
    single = mode == "1"
    first = resolver.ask("  Atom/group A", expect_single=single)
    second = resolver.ask("  Atom/group B", expect_single=single)
    default_name = f"d_{first.alias}_{second.alias}"[:40]
    name = prompt.text("  Name", default=default_name)
    entry = {"name": name, "atoms": [first.alias, second.alias],
             "label": f"{first.description.split(' (')[0]} – "
                      f"{second.description.split(' (')[0]}"}
    if mode == "2":
        entry["mode"] = "com"
    elif mode == "3":
        entry["mode"] = "min"
    threshold = prompt.number("  Threshold in A (for the % of frames below it)")
    if threshold is not None:
        entry["threshold"] = threshold
    section["pairs"].append(entry)
    draft.observables.append(name)
    prompt.ok(f"distance added: '{name}'")


def _add_geometry(prompt: Prompt, resolver: AtomResolver, draft: _Draft,
                  key: str, n_atoms: int, prefix: str) -> None:
    section = _section(draft, key, {"enabled": True, "definitions": []})
    atoms = [resolver.ask(f"  Atom {i + 1} of {n_atoms}") for i in range(n_atoms)]
    default_name = f"{prefix}_{atoms[0].alias}"[:40]
    name = prompt.text("  Name", default=default_name)
    section["definitions"].append({
        "name": name,
        "atoms": [a.alias for a in atoms],
        "label": " – ".join(a.description.split(" (")[0] for a in atoms),
    })
    draft.observables.append(name)
    prompt.ok(f"added '{name}'")


def _add_angle(prompt, resolver, draft) -> None:
    _add_geometry(prompt, resolver, draft, "angles", 3, "a")


def _add_dihedral(prompt, resolver, draft) -> None:
    _add_geometry(prompt, resolver, draft, "dihedrals", 4, "chi")


def _add_hbond(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "hbonds", {
        "enabled": True, "d_a_cutoff": 3.5, "d_h_a_angle_cutoff": 150, "pairs": [],
    })
    prompt.say("  The donor is the heavy atom (N, O...), not the hydrogen.")
    donor = resolver.ask("  Donor (heavy atom)")
    acceptor = resolver.ask("  Acceptor", expect_single=False)
    entry = {"name": prompt.text("  Name", default=f"hb_{donor.alias}_{acceptor.alias}"[:40]),
             "donor": donor.alias, "acceptor": acceptor.alias}
    if prompt.yes_no("  Specify which hydrogen? "
                     "(by default the best oriented one is used)", default=False):
        entry["hydrogen"] = resolver.ask("  Hydrogen").alias
    section["pairs"].append(entry)
    draft.observables.append(entry["name"])
    prompt.ok(f"hydrogen bond added: '{entry['name']}'")


def _add_rmsd(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "rmsd", {"enabled": True, "ref_frame": 0, "groups": []})
    prompt.say("  Selection to MEASURE (e.g. backbone, resname LIG, or an active-site group).")
    measured = resolver.ask("  Measured selection", expect_single=False)
    entry = {"name": prompt.text("  Name", default=measured.alias),
             "selection": measured.alias}
    if prompt.yes_no("  Fit on a different selection? "
                     "(local RMSD: fit on the protein, measure the ligand)",
                     default=False):
        fit = resolver.ask("  Selection of ajuste", expect_single=False)
        entry["superposition"] = fit.alias
    section["groups"].append(entry)
    draft.observables.append(entry["name"])
    prompt.ok(f"RMSD added: '{entry['name']}'")


def _add_rmsf(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    selection = prompt.text("  Selection", default="protein and name CA")
    entry = {"enabled": True, "selection": selection, "align": True}
    highlight = prompt.text("  Residues to highlight (numbers separated by spaces)",
                            default="", allow_empty=True)
    if highlight.strip():
        entry["highlight"] = [int(x) for x in highlight.split() if x.isdigit()]
    draft.analyses["rmsf"] = entry
    prompt.ok("per-residue RMSF added")


def _add_rgyr(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "radius_of_gyration", {"enabled": True, "groups": []})
    group = resolver.ask("  Selection", expect_single=False)
    name = prompt.text("  Name", default=f"rg_{group.alias}"[:40])
    section["groups"].append({"name": name, "selection": group.alias})
    draft.observables.append(name)
    prompt.ok(f"radius of gyration added: '{name}'")


def _add_rdf(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    section = _section(draft, "rdf", {"enabled": True, "pairs": []})
    first = resolver.ask("  Selection central (g1)", expect_single=False)
    second = resolver.ask("  Environment selection (g2, e.g. the water oxygen)",
                          expect_single=False)
    name = prompt.text("  Name", default=f"rdf_{first.alias}_{second.alias}"[:40])
    rmax = prompt.number("  Maximum radius in A", default=12.0)
    section["pairs"].append({"name": name, "g1": first.alias, "g2": second.alias,
                             "nbins": 120, "range": [0.0, float(rmax)]})
    prompt.ok(f"RDF added: '{name}'")


def _add_clustering(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    group = resolver.ask("  Selection to cluster on "
                         "(e.g. the active site without hydrogens)", expect_single=False)
    n_clusters = int(prompt.number("  Number of clusters", default=3, cast=int))
    draft.analyses["clustering"] = {
        "enabled": True, "selection": group.alias, "method": "hierarchical",
        "n_clusters": n_clusters, "write_structures": True,
    }
    prompt.ok(f"clustering added with {n_clusters} clusters")


def _add_map(prompt: Prompt, resolver: AtomResolver, draft: _Draft) -> None:
    if len(draft.observables) < 2:
        prompt.warn("At least two observables must already be defined "
                    "(distances, angles, RMSD...). Add them first.")
        return
    prompt.say(f"  Available observables: {', '.join(draft.observables)}")
    section = _section(draft, "free_energy_maps",
                       {"enabled": True, "temperature": 300.0, "maps": []})
    while True:
        x = prompt.text("  X axis", default=draft.observables[0])
        if x in draft.observables:
            break
        prompt.warn(f"'{x}' is not defined.")
    while True:
        y = prompt.text("  Y axis", default=draft.observables[1])
        if y in draft.observables:
            break
        prompt.warn(f"'{y}' is not defined.")
    name = prompt.text("  Name", default=f"fes_{x}_{y}"[:40])
    free_energy = prompt.yes_no("  Convert to apparent free energy (-kT ln P)?",
                                default=True)
    section["maps"].append({"name": name, "x": x, "y": y, "bins": 60,
                            "free_energy": free_energy})
    prompt.ok(f"map added: '{name}'")
