"""Local graphical interface with a 3D structure viewer.

One entry point — ``md-analyzer gui`` — that replaces the wizard/check/run
dance: the structure is shown in the browser, you click the atoms you want to
measure, the automatic detection proposes what is already there, and the
figures come back in the same window.

Deliberately built on the standard library (``http.server``) and a vendored
copy of 3Dmol.js, so it runs on a cluster with no internet access and no extra
Python dependencies.  Over SSH:

    ssh -L 8765:localhost:8765 user@cluster
    md-analyzer gui --top system.prmtop --traj prod.nc --no-browser
"""

from __future__ import annotations

import json
import threading
import traceback
import webbrowser
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import numpy as np

from ..exceptions import MDInteractionsError

__all__ = ["serve", "GuiState"]

_STATIC = Path(__file__).parent / "static"
_MIME = {".html": "text/html; charset=utf-8", ".js": "application/javascript",
         ".css": "text/css", ".png": "image/png", ".pdf": "application/pdf",
         ".svg": "image/svg+xml", ".json": "application/json"}


@dataclass
class GuiState:
    """Everything the server needs to answer requests."""

    topology: Path
    trajectory: list[Path]
    stride: int = 1
    universe: object | None = None
    system: object | None = None
    subset_indices: np.ndarray | None = None   # PDB serial -> universe index
    job: dict = field(default_factory=lambda: {"status": "idle", "message": "",
                                               "result": None})
    results_dir: Path | None = None

    # -- lazily built objects -------------------------------------------- #
    def load(self) -> None:
        import MDAnalysis as mda

        if self.universe is None:
            args = [str(self.topology)] + [str(p) for p in self.trajectory]
            self.universe = mda.Universe(*args)

    def build_system(self):
        """An :class:`~md_interactions.system.MDSystem` for the explore calls."""
        from ..config import Config
        from ..system import load_system

        config = Config.from_dict({
            "system": {
                "topology": str(self.topology),
                "trajectory": [str(p) for p in self.trajectory] or [str(self.topology)],
                "frames": {"stride": int(self.stride)},
            },
            "output": {"directory": str(self.results_dir or "results")},
        })
        return load_system(config, verbose=False)


# --------------------------------------------------------------------------- #
# structure serialisation
# --------------------------------------------------------------------------- #
def _structure_pdb(state: GuiState, include_waters: bool) -> tuple[str, list[int]]:
    """Frame 0 as PDB text, plus the universe index of every written atom."""
    state.load()
    universe = state.universe
    selection = "protein or not (resname WAT HOH SOL TIP3 T3P)"
    if include_waters:
        selection = "all"
    group = universe.select_atoms(selection)

    if len(state.trajectory):
        universe.trajectory[0]

    # Written by hand against the PDB column specification: the writer shipped
    # with MDAnalysis puts resName in columns 17-19 instead of 18-20, which the
    # viewer parses as a truncated residue name.
    if group.n_atoms > 99999:
        raise MDInteractionsError(
            f"{group.n_atoms} atoms exceed the 5-digit PDB serial field. "
            "Load the structure without waters, or restrict the selection."
        )

    lines = ["REMARK   generated by md_interactions gui"]
    masses = np.asarray(group.masses, dtype=float)
    for order, atom in enumerate(group):
        serial = order + 1                     # the browser maps back with this
        name = str(atom.name)[:4]
        # names shorter than 4 characters start in column 14 by convention
        name_field = f"{name:<4s}" if len(name) == 4 else f" {name:<3s}"
        x, y, z = (float(v) for v in atom.position)
        element = _element_symbol(float(masses[order]))
        lines.append(
            f"ATOM  {serial:5d} {name_field}"          # 1-16
            f" {str(atom.resname)[:3]:>3s}"            # 17 altLoc + 18-20 resName
            f" A{int(atom.resid) % 10000:4d} "         # 21 + 22 chain + 23-26 + 27
            f"   {x:8.3f}{y:8.3f}{z:8.3f}"             # 28-30 + coordinates
            f"  1.00  0.00          {element:>2s}"     # occupancy, B, element
        )
    lines.append("END")
    return "\n".join(lines), [int(a.index) for a in group]


def _element_symbol(mass: float) -> str:
    for limit, symbol in ((1.5, "H"), (13.0, "C"), (14.5, "N"), (16.5, "O"),
                          (19.5, "F"), (24.5, "NA"), (31.0, "P"), (32.6, "S"),
                          (36.0, "CL")):
        if mass <= limit:
            return symbol
    return "C"


# --------------------------------------------------------------------------- #
# request handling
# --------------------------------------------------------------------------- #
class _Handler(BaseHTTPRequestHandler):
    state: GuiState = None            # injected by :func:`serve`

    def log_message(self, *_args) -> None:      # keep the console clean
        pass

    # -- helpers -- #
    def _send(self, payload: bytes, content_type: str, status: int = 200) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def _json(self, data, status: int = 200) -> None:
        self._send(json.dumps(data).encode("utf-8"), "application/json", status)

    def _body(self) -> dict:
        length = int(self.headers.get("Content-Length", 0))
        if not length:
            return {}
        return json.loads(self.rfile.read(length).decode("utf-8"))

    # -- routes -- #
    def do_GET(self) -> None:                    # noqa: N802
        parsed = urlparse(self.path)
        route = parsed.path
        query = parse_qs(parsed.query)
        try:
            if route in ("/", "/index.html"):
                self._send((_STATIC / "index.html").read_bytes(), _MIME[".html"])
            elif route.startswith("/static/"):
                self._static(route[len("/static/"):])
            elif route == "/api/system":
                self._json(_system_info(self.state))
            elif route == "/api/structure":
                include = query.get("waters", ["0"])[0] == "1"
                pdb, indices = _structure_pdb(self.state, include)
                self.state.subset_indices = np.asarray(indices, dtype=int)
                self._json({"pdb": pdb, "indices": indices})
            elif route == "/api/job":
                self._json(self.state.job)
            elif route.startswith("/results/"):
                self._result_file(route[len("/results/"):])
            else:
                self._json({"error": "not found"}, 404)
        except Exception as exc:                 # pragma: no cover - defensive
            self._json({"error": f"{type(exc).__name__}: {exc}"}, 500)

    def do_POST(self) -> None:                   # noqa: N802
        route = urlparse(self.path).path
        try:
            body = self._body()
            if route == "/api/explore":
                self._json(_explore(self.state, body))
            elif route == "/api/run":
                _start_run(self.state, body)
                self._json({"status": "started"})
            else:
                self._json({"error": "not found"}, 404)
        except MDInteractionsError as exc:
            self._json({"error": str(exc)}, 400)
        except Exception as exc:
            self._json({"error": f"{type(exc).__name__}: {exc}",
                        "traceback": traceback.format_exc()}, 500)

    # -- static/results -- #
    def _static(self, name: str) -> None:
        path = (_STATIC / name).resolve()
        if not str(path).startswith(str(_STATIC.resolve())) or not path.is_file():
            self._json({"error": "not found"}, 404)
            return
        self._send(path.read_bytes(), _MIME.get(path.suffix, "application/octet-stream"))

    def _result_file(self, name: str) -> None:
        root = (self.state.results_dir or Path("results")).resolve()
        path = (root / name).resolve()
        if not str(path).startswith(str(root)) or not path.is_file():
            self._json({"error": "not found"}, 404)
            return
        self._send(path.read_bytes(), _MIME.get(path.suffix, "application/octet-stream"))


# --------------------------------------------------------------------------- #
# API implementations
# --------------------------------------------------------------------------- #
def _system_info(state: GuiState) -> dict:
    state.load()
    universe = state.universe
    protein = universe.select_atoms("protein")
    ligands = []
    water = {"WAT", "HOH", "SOL", "TIP3", "T3P"}
    protein_resnames = set(protein.residues.resnames)
    seen = set()
    for residue in universe.residues:
        name = str(residue.resname)
        if name in protein_resnames or name in water or name in seen:
            continue
        seen.add(name)
        ligands.append({"resname": name, "resid": int(residue.resid),
                        "n_atoms": int(residue.atoms.n_atoms)})
    n_frames = len(universe.trajectory) if state.trajectory else 0
    return {
        "topology": str(state.topology),
        "trajectory": [str(p) for p in state.trajectory],
        "n_atoms": int(universe.atoms.n_atoms),
        "n_residues": int(universe.residues.n_residues),
        "n_protein_residues": int(protein.residues.n_residues),
        "n_frames": n_frames,
        "ligands": ligands[:20],
        "stride": state.stride,
    }


def _explore(state: GuiState, body: dict) -> dict:
    from .. import explore as ex

    system = state.build_system()
    mode = body.get("mode", "contacts")
    region = body.get("region") or ex.DEFAULT_REGION

    if mode == "contacts":
        table = ex.find_contacts(
            system, region=region, cutoff=float(body.get("cutoff", 4.0)),
            waters=body.get("waters", "aggregate"),
            min_occupancy=float(body.get("min_occupancy", 5.0)), verbose=False,
        )
        return {"mode": mode, "rows": _records(table)}

    if mode == "changes":
        bonds = ex.detect_bond_changes(system, verbose=False)
        protons = ex.detect_proton_transfers(system, verbose=False)
        return {"mode": mode, "bonds": _records(bonds), "protons": _records(protons)}

    raise MDInteractionsError(f"Unknown explore mode '{mode}'.")


def _records(table) -> list[dict]:
    if table is None or getattr(table, "empty", True):
        return []
    clean = table.replace({np.nan: None})
    return json.loads(clean.to_json(orient="records"))


def _start_run(state: GuiState, body: dict) -> None:
    """Launch the analysis in a worker thread so the UI stays responsive."""
    if state.job["status"] == "running":
        raise MDInteractionsError("An analysis is already running.")
    state.job = {"status": "running", "message": "Preparing...", "result": None}

    def worker() -> None:
        try:
            state.job["message"] = "Running the analysis..."
            result = _run_analysis(state, body)
            state.job = {"status": "done", "message": "Done", "result": result}
        except Exception as exc:
            state.job = {"status": "error",
                         "message": f"{type(exc).__name__}: {exc}", "result": None}

    threading.Thread(target=worker, daemon=True).start()


def _run_analysis(state: GuiState, body: dict) -> dict:
    """Build a configuration from the interactions picked in the browser."""
    from ..config import Config
    from ..runner import run_analyses

    interactions = body.get("interactions", [])
    if not interactions:
        raise MDInteractionsError("No interactions selected.")

    results_dir = Path(body.get("output", "results_gui")).resolve()
    state.results_dir = results_dir

    selections: dict[str, str] = {}
    distances: list[dict] = []
    angles: list[dict] = []
    dihedrals: list[dict] = []

    for entry in interactions:
        aliases = []
        for atom in entry["atoms"]:
            alias = _alias(atom)
            selections[alias] = f"resid {atom['resid']} and name {atom['name']}"
            aliases.append(alias)
        record = {"name": entry.get("name") or f"obs_{len(distances) + 1}",
                  "atoms": aliases,
                  "label": " – ".join(f"{a['resname']}{a['resid']}:{a['name']}"
                                      for a in entry["atoms"])}
        if entry.get("threshold"):
            record["threshold"] = float(entry["threshold"])
        kind = entry.get("kind", "distance")
        if kind == "distance":
            distances.append(record)
        elif kind == "angle":
            record.pop("threshold", None)
            angles.append(record)
        elif kind == "dihedral":
            record.pop("threshold", None)
            dihedrals.append(record)

    analyses: dict = {}
    if distances:
        analyses["distances"] = {"enabled": True, "pairs": distances}
    if angles:
        analyses["angles"] = {"enabled": True, "definitions": angles}
    if dihedrals:
        analyses["dihedrals"] = {"enabled": True, "definitions": dihedrals}

    config = Config.from_dict({
        "system": {
            "topology": str(state.topology),
            "trajectory": [str(p) for p in state.trajectory],
            "frames": {"stride": int(body.get("stride", state.stride))},
            "time": {"dt": None, "unit": body.get("time_unit", "ps")},
        },
        "output": {"directory": str(results_dir), "formats": ["png", "pdf"],
                   "dpi": 200},
        "selections": selections,
        "analyses": analyses,
        "report": {"enabled": True, "formats": ["markdown", "html"]},
    })

    output = run_analyses(config, verbose=False, strict=False)
    plots = sorted(p.name for p in (results_dir / "plots").glob("*.png"))
    summary = _records(output.summary) if output.summary is not None else []
    return {
        "plots": plots,
        "summary": summary,
        "failures": [{"analysis": name, "message": message}
                     for name, message in output.failures],
        "directory": str(results_dir),
    }


def _alias(atom: dict) -> str:
    raw = f"{atom['resname']}{atom['resid']}_{atom['name']}"
    return "".join(c if (c.isalnum() or c == "_") else "_" for c in raw)


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def _refuse_if_port_busy(port: int) -> None:
    """Fail loudly when another instance is already answering on ``port``."""
    import socket

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.settimeout(0.4)
        if probe.connect_ex(("127.0.0.1", port)) == 0:
            raise MDInteractionsError(
                f"Port {port} is already serving: another `md-analyzer gui` is "
                "running. Close it, or start this one with --port <other>."
            )


def serve(topology, trajectory=None, port: int = 8765, stride: int = 1,
          open_browser: bool = True, results_dir="results_gui") -> None:
    """Start the local server (blocking) and optionally open the browser."""
    state = GuiState(topology=Path(topology),
                     trajectory=[Path(p) for p in (trajectory or [])],
                     stride=stride, results_dir=Path(results_dir).resolve())
    if not state.topology.is_file():
        raise MDInteractionsError(f"Topology not found: {state.topology}")

    # On Windows SO_REUSEADDR lets a second server bind the same port silently,
    # so requests would keep being answered by the older (stale) process.
    _refuse_if_port_busy(port)

    handler = type("_BoundHandler", (_Handler,), {"state": state})
    server = ThreadingHTTPServer(("127.0.0.1", port), handler)
    url = f"http://localhost:{port}"
    print(f"[md_interactions] GUI at {url}")
    print("[md_interactions] Ctrl-C to quit")
    if open_browser:
        threading.Timer(0.6, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[md_interactions] closed")
    finally:
        server.server_close()
